name: CI github pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/start_workflow.txt'
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency: 
      group: "pages"
      cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for all the files to be saved to the repository
        run: |
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get url
        run: |
          # ---------------------------------------
          BUCKET_NAME=$(cat src/start_workflow.txt | cut -d '|' -f 1);
          echo "BUCKET_NAME = $BUCKET_NAME";
          # ---------------------------------------
          URL=$(cat src/start_workflow.txt | cut -d '|' -f 2);
          echo "URL = $URL";
          # ---------------------------------------
         

          # ---------------------------------------


          # ---------------------------------------

          
     
